# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
